### ISSUE TITLE
every click on the list makes the screen flash black for a second

### ISSUE THREAD

**Issue by StealthHydra179** [MCPI-Devs/MCPIL-R#5] opened 2020-12-09 01:21 UTC

**Comment by Alvarito050506** [comment] 2020-12-13 14:32
Ok, this one is really weird :thinking:.

**Comment by TheBrokenRail** [comment] 2021-01-11 21:24
Can you reproduce this?

**Comment by StealthHydra179** [comment] 2021-01-13 02:01
im on mac

**Comment by TheBrokenRail** [comment] 2021-01-13 20:59
Since this project requires Linux to run anyways, I am closing this issue.

**Closed by TheBrokenRail** 2021-01-13 20:59 UTC
Labels: bug, enhancement
